name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: actions/cache@preview
      id: cache
      with:
        path: docker-cache
        key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-docker-
    - name: Load cached Docker layers
      run: |
        if [ -d "docker-cache" ]; then
          cat docker-cache/x* > my-image.tar
          docker load < my-image.tar
          rm -fr docker-cache
        fi
    - name: Build image
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        docker build --cache-from my-image -t my-image .
        docker save my-image > my-image.tar
        mkdir docker-cache
        split -b 100m my-image.tar docker-cache/x

    - name: Run the compose network
      run: make run
    - name: Run the tests
      run: docker-compose exec -T gen3-cli /bin/bash -c 'source ~/.bashrc && make tests'
