name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: whoan/docker-build-with-cache-action@v2
      with:
        username: "${{ secrets.DOCKER_USERNAME }}"
        password: "${{ secrets.DOCKER_PASSWORD }}"
        image_name: codeontap/gen3-cli
        image_tag: latest
        context: ./gen3-cli

    - name: Tag image
      run: |
        docker tag codeontap/gen3-cli:latest gen3-cli:latest

    - name: Run the compose network
      run: docker-compose up -d
    - name: Run the tests
      run: docker-compose exec -T gen3-cli /bin/bash -c 'source ~/.bashrc && make tests'
